### ISSUE TITLE
How do you change the drag handle?

### ISSUE THREAD

**Issue by hybridwebdev** [michitaro/vue-window#16]
I want to be able to define my own element as the drag handle, instead of using the title bar, and after hours of going through code, cannot for the life of me figure out how. I apologize, but I can't wrap my head around typescript, which is the major barrier i'm experiencing here.

**Comment by hybridwebdev** [comment]
Seriously still no response to this? It's been a month...just looking for some advice please.

**Comment by michitaro** [comment]
Sorry for the late.
I added a [sample](https://michitaro.github.io/vue-window/?Sample8) for drag handle, but it is not well integrated with vue-window.

**Comment by hybridwebdev** [comment]
Ahh perfect, this answers my question. Thank you :)
