### ISSUE TITLE
How to use without Webpack?

### ISSUE THREAD

**Issue by Matheeus97** [michitaro/vue-window#17]
Is possible to get a build version of vue-window? I'm using Vue without Single File Components and Webpack, so I can't use this pack.

How to build it to single js?

**Comment by michitaro** [comment]
> How to build it to single js?
```sh
git clone https://github.com/michitaro/vue-window.git
cd vue-window
npm install
npm run standalone
open standalone/dist
```

**Comment by Matheeus97** [comment]
Seems that now the :closeButton doesn't work anymore:

<hsc-window title="Debug" :closeButton="true">

**Comment by michitaro** [comment]
Use ```:close-button``` instead of ```:closeButton```.
See [here](https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case).
