### ISSUE TITLE
feature request: set height, width by default

### ISSUE THREAD

**Issue by danstans** [michitaro/vue-window#2]
Unless i'm mistaken, I am unable to set the default height and width of the vue-window. I am only able to set the min/max height/width. Is this by design?

**Comment by michitaro** [comment]
I added properties "initialWidth" and "initialHeight" minutes ago.
See https://github.com/michitaro/vue-window/blob/master/example/src/sample4.vue#L12

I hope this change will help you.

**Comment by danstans** [comment]
You are the best! Thank you very much. If you don't mind me asking, I am new to using other people's packages in my own projects. If I am to make changes to your work what is the best way to do that? 

Should I fork the repository or do I just edit the files in my node_modules directly?

**Comment by michitaro** [comment]
> Should I fork the repository or do I just edit the files in my node_modules directly?

I don't recommend editing files in node_modules directrly because
1. the files there are already compiled, so it's difficult to edit.
1. files in node_modules are usually not git-ignored.

**Comment by michitaro** [comment]
(edited)

**Comment by danstans** [comment]
Perfect, I will make changes accordingly and use this on my website. Thank you for the exhaustive write up. ありがとうございました!
