### ISSUE TITLE
Catching Dragging Event

### ISSUE THREAD

**Issue by esgungor** [michitaro/vue-window#28]
Hello,
I tried to reach the dragging event. I could not find how to control the catch dragging event. I found the onMove function inside of the source code. However, it wouldn't work. Has anyone tried that before. Thanks for your help

**Comment by michitaro** [comment]
The window component emits `move-start` and `move-end` events when it starts and ends its movement.
https://github.com/michitaro/vue-window/blob/95efd3a61aab7d8e4b663f6cc6dc42c630595fff/src/window/script.ts#L140-L141
It also fires the `update:left` and `update:top` events when the position is changed while moving.
https://github.com/michitaro/vue-window/blob/95efd3a61aab7d8e4b663f6cc6dc42c630595fff/src/window/script.ts#L260-L261

**Comment by esgungor** [comment]
Oh thanks, yes that is worked!
